//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CrossVersionObjectReference) DeepCopyInto(out *CrossVersionObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CrossVersionObjectReference.
func (in *CrossVersionObjectReference) DeepCopy() *CrossVersionObjectReference {
	if in == nil {
		return nil
	}
	out := new(CrossVersionObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodChaosMonkey) DeepCopyInto(out *PodChaosMonkey) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodChaosMonkey.
func (in *PodChaosMonkey) DeepCopy() *PodChaosMonkey {
	if in == nil {
		return nil
	}
	out := new(PodChaosMonkey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodChaosMonkey) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodChaosMonkeyConditions) DeepCopyInto(out *PodChaosMonkeyConditions) {
	*out = *in
	if in.MinPods != nil {
		in, out := &in.MinPods, &out.MinPods
		*out = new(int32)
		**out = **in
	}
	if in.MinTimeRunning != nil {
		in, out := &in.MinTimeRunning, &out.MinTimeRunning
		*out = new(int32)
		**out = **in
	}
	if in.MinTimeRandom != nil {
		in, out := &in.MinTimeRandom, &out.MinTimeRandom
		*out = new(int32)
		**out = **in
	}
	if in.MaxTimeRandom != nil {
		in, out := &in.MaxTimeRandom, &out.MaxTimeRandom
		*out = new(int32)
		**out = **in
	}
	if in.GracePeriodSeconds != nil {
		in, out := &in.GracePeriodSeconds, &out.GracePeriodSeconds
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodChaosMonkeyConditions.
func (in *PodChaosMonkeyConditions) DeepCopy() *PodChaosMonkeyConditions {
	if in == nil {
		return nil
	}
	out := new(PodChaosMonkeyConditions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodChaosMonkeyList) DeepCopyInto(out *PodChaosMonkeyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PodChaosMonkey, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodChaosMonkeyList.
func (in *PodChaosMonkeyList) DeepCopy() *PodChaosMonkeyList {
	if in == nil {
		return nil
	}
	out := new(PodChaosMonkeyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodChaosMonkeyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodChaosMonkeySpec) DeepCopyInto(out *PodChaosMonkeySpec) {
	*out = *in
	if in.TargetRef != nil {
		in, out := &in.TargetRef, &out.TargetRef
		*out = new(CrossVersionObjectReference)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = new(PodChaosMonkeyConditions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodChaosMonkeySpec.
func (in *PodChaosMonkeySpec) DeepCopy() *PodChaosMonkeySpec {
	if in == nil {
		return nil
	}
	out := new(PodChaosMonkeySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodChaosMonkeyStatus) DeepCopyInto(out *PodChaosMonkeyStatus) {
	*out = *in
	if in.LastEvictionAt != nil {
		in, out := &in.LastEvictionAt, &out.LastEvictionAt
		*out = (*in).DeepCopy()
	}
	if in.NumberOfEvictions != nil {
		in, out := &in.NumberOfEvictions, &out.NumberOfEvictions
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodChaosMonkeyStatus.
func (in *PodChaosMonkeyStatus) DeepCopy() *PodChaosMonkeyStatus {
	if in == nil {
		return nil
	}
	out := new(PodChaosMonkeyStatus)
	in.DeepCopyInto(out)
	return out
}
