# permissions for end users to edit podchaosmonkeys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podchaosmonkey-editor-role
rules:
- apiGroups:
  - testing.chaos.io
  resources:
  - podchaosmonkeys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - testing.chaos.io
  resources:
  - podchaosmonkeys/status
  verbs:
  - get
