apiVersion: "testing.chaos.io/v1"
kind: PodChaosMonkey
metadata:
  name: hamster-chaos
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: hamster
  conditions:
    minPods: 2
    minTimeRunning: 10
    minTimeRandom: 10
    maxTimeRandom: 30
